### ISSUE TITLE
Individual kernel commands no longer supported?

### ISSUE THREAD

**Issue by FlareHAX0R** [TARDIX/Kernel#11]
Appearently, the kernel does not seperate kernel arguments by spaces anymore.
(e.x - kernel argument "kernel_root=kernel/ quiet splash" seems to make quiet splash count for kernel_root now, causing a file not found error.)

And also, i tried seperating them by a comma, it seems to require an =.

**Comment by DemHydraz** [comment]
oh, ok.

**Comment by DemHydraz** [comment]
Fixed.
