### ISSUE TITLE
IO Streams

### ISSUE THREAD

**Issue by SquidDev** [TARDIX/Kernel#8]
It would be great if the the IO library supported stdin/stdout/stderr. To quote the [Lua docs](http://www.lua.org/pil/21.2.html):

> The I/O library also offers handles for the three predefined C streams: io.stdin, io.stdout, and io.stderr.  So, you can send a message directly to the error stream with a code like this:

 > ```
 io.stderr:write(message)
```

This would mean the shell could implement redirects and pipes (similar to [ClamShell](http://github.com/Team-CC-Corp/ClamShell)). 

I'm happy to get put together a PR on this, I just would like to see your thoughts on this first.

**Comment by DemHydraz** [comment]
Hmm, yes. This would be a good idea, indeed. I'll have a shot at implementing it.

Thanks for contribuiting,
~ DemHydraz.
